import type { Product } from './types'

export const products: Product[] = [
    {
        id: '1',
        name: 'Coffee - Small',
        price: 2.5,
        category: 'drinks',
        sku: 'DRK-001',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '2',
        name: 'Coffee - Medium',
        price: 3.5,
        category: 'drinks',
        sku: 'DRK-002',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '3',
        name: 'Coffee - Large',
        price: 4.5,
        category: 'drinks',
        sku: 'DRK-003',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '4',
        name: 'Espresso',
        price: 3.0,
        category: 'drinks',
        sku: 'DRK-004',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '5',
        name: 'Cappuccino',
        price: 4.0,
        category: 'drinks',
        sku: 'DRK-005',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '6',
        name: 'Latte',
        price: 4.5,
        category: 'drinks',
        sku: 'DRK-006',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '7',
        name: 'Croissant',
        price: 3.0,
        category: 'bakery',
        sku: 'BKY-001',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '8',
        name: 'Chocolate Muffin',
        price: 3.5,
        category: 'bakery',
        sku: 'BKY-002',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '9',
        name: 'Blueberry Muffin',
        price: 3.5,
        category: 'bakery',
        sku: 'BKY-003',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '10',
        name: 'Bagel',
        price: 2.5,
        category: 'bakery',
        sku: 'BKY-004',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '11',
        name: 'Sandwich - Turkey',
        price: 6.5,
        category: 'food',
        sku: 'FD-001',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '12',
        name: 'Sandwich - Ham',
        price: 6.5,
        category: 'food',
        sku: 'FD-002',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '13',
        name: 'Sandwich - Veggie',
        price: 5.5,
        category: 'food',
        sku: 'FD-003',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '14',
        name: 'Salad - Caesar',
        price: 7.0,
        category: 'food',
        sku: 'FD-004',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '15',
        name: 'Salad - Garden',
        price: 6.0,
        category: 'food',
        sku: 'FD-005',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '16',
        name: 'Bottled Water',
        price: 1.5,
        category: 'drinks',
        sku: 'DRK-007',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '17',
        name: 'Soda',
        price: 2.0,
        category: 'drinks',
        sku: 'DRK-008',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '18',
        name: 'Iced Tea',
        price: 2.5,
        category: 'drinks',
        sku: 'DRK-009',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '19',
        name: 'Chocolate Chip Cookie',
        price: 2.0,
        category: 'bakery',
        sku: 'BKY-005',
        image: '/placeholder.svg?height=200&width=200',
    },
    {
        id: '20',
        name: 'Oatmeal Cookie',
        price: 2.0,
        category: 'bakery',
        sku: 'BKY-006',
        image: '/placeholder.svg?height=200&width=200',
    },
]
